language: node_js
node_js:
- '6'
- '4'
- '0.12'
dist: trusty
addons:
  chrome: stable
env:
  global:
    # GH_TOKEN=xxx
  - secure: fPH8vFr+1uSuFj2B0m/BOeXJQS25zKWrfzscHB4AYHAduHjQE/cO0M4Z9p2K16JnnL7700LPMs5DXAOd0qqTeFIDkn1I6VZI6uUTUnFpa48trtPEUVAQZkIe+TQwvOHVn1au1qUoL4TkenuvvltlfYYOZ63SPYZUaS0XD9jCM2U=
    # EMAIL=xxx
  - secure: QoPDPcuWHSS9u12cg8T5JmBNNrnNwnkMZBXYMaw3rQjyOiqOLe/bA5bDBg8/NyiqnOF5ik6zEGKqn2CSK22TYPbycCzmlMwAOKNfTWK+nFwek53QXI+CUH9OpAIU9Xm/03Fv80kLhZ/kobP59NsX+qFGTMZaqeiA1hTdEElYsGs=
    # COVERALLS_TOKEN=xxx
  - secure: QVt890y6/RewLSzvJmEx7nljetYmKzDjHYKMtYZ/yzCAFGIgOKS4FcjSf/XFgx4UHEIflPRTPtJE8EHVdxzM5Le3FlGw3jdL6/LUBQ6DNSHQCMvF8lkb25dswresDTnS+HWSzyda7s+woXsYYvHpF70i7pkaHw8jRBo3t0k3Rbs=
script:
- npm_config_coverage=y npm test
- ./minify.sh
- MINIFIED=y npm test
- ./commit-minified.sh
- COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
- ./build-pages.sh
