language: node_js
node_js:
- '10'
- '8'
- '6'
- '4'
- '0.12'
dist: trusty
addons:
  chrome: stable
env:
  global:
    # GH_TOKEN=xxx
  - secure: fPH8vFr+1uSuFj2B0m/BOeXJQS25zKWrfzscHB4AYHAduHjQE/cO0M4Z9p2K16JnnL7700LPMs5DXAOd0qqTeFIDkn1I6VZI6uUTUnFpa48trtPEUVAQZkIe+TQwvOHVn1au1qUoL4TkenuvvltlfYYOZ63SPYZUaS0XD9jCM2U=
    # COVERALLS_TOKEN=xxx
  - secure: QVt890y6/RewLSzvJmEx7nljetYmKzDjHYKMtYZ/yzCAFGIgOKS4FcjSf/XFgx4UHEIflPRTPtJE8EHVdxzM5Le3FlGw3jdL6/LUBQ6DNSHQCMvF8lkb25dswresDTnS+HWSzyda7s+woXsYYvHpF70i7pkaHw8jRBo3t0k3Rbs=

jobs:
  include:
    - stage: test
      script: npm_config_coverage=y npm test
    - stage: upload-coverage
      node_js: "10"
      script: COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
    - stage: minify
      script: ./minify.sh
    - stage: test-minified
    - script: MINIFIED=y npm test
    - stage: commit-minified
      node_js: "10"
      script: ./commit-minified.sh
    - stage: deploy-docs
      node_js: "10"
      script: ./build-docs.sh
      deploy:
        provider: pages
        name: 'Travis CI'
        github-token: $GH_TOKEN
        skip-cleanup: true
        keep-history: true
        local-dir: docs
        on:
          branch: master